spring:
  application:
    name: temple-system
  profiles:
    active: dev
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

server:
  servlet:
    context-path: /system

jwt:
  secret: temple-secret-key-for-jwt-token-generation-2024
  expiration: 86400000
